/* **********************************************************
	DDL Create
	Schéma MRD:	"Village Vacances VERSION 1"
	Auteur:		Dominique Septembre + Charles-Edouard Beaudet - Cégep de Ste-Foy  	
***********************************************************/
/*
	Création des tables et séquences
*/
/***********************************************************
	Table "CATEGORIE_VILLAGE"
***********************************************************/
CREATE TABLE CATEGORIE_VILLAGE
(
	NO_CATEGORIE 	SMALLINT 		NOT NULL,
	DESCRIPTION 	VARCHAR2(50)	NOT NULL,
	CONSTRAINT PK_CATEGORIE_VILLAGE
					PRIMARY KEY(NO_CATEGORIE),
	CONSTRAINT U1_DESCRIPTION_CATEGORIE_VILLAGE
					UNIQUE (DESCRIPTION)
	CONSTRAINT NO_CATEGORIE_MIN_MAX
				CHECK (NO_CATEGORIE BETWEEN 1 AND 5)

);
/***********************************************************
	Table "TYPE_LOGEMENT"
***********************************************************/
CREATE TABLE TYPE_LOGEMENT
(
	CODE_TYPE_LOGEMENT	VARCHAR2(2)		NOT NULL,
	DESCRIPTION 		VARCHAR2(35)	NOT NULL,
	NB_MAX_PERSONNES	SMALLINT 		NOT NULL,
	CONSTRAINT PK_TYPE_LOGEMENT
						PRIMARY KEY (CODE_TYPE_LOGEMENT),
	CONSTRAINT U1_DESCRIPTION_TYPE_LOGEMENT
					UNIQUE (DESCRIPTION),
	CONSTRAINT TYPE_LOGEMENT_FORMAT
					CHECK (), -- À COMPLÉTER
	CONSTRAINT MAX_NB_MAX_PERSONNES
					CHECK (NB_MAX_PERSONNES <= 10)
);
/***********************************************************
	Table "VILLAGE"
***********************************************************/
CREATE TABLE VILLAGE
(
	NOM_VILLAGE 	VARCHAR2(15)	NOT NULL,
	NO_CATEGORIE	SMALLINT		NOT NULL,
	VILLE 			VARCHAR2(10) 	NOT NULL,
	PAYS 			VARCHAR2(10)	NOT NULL,
	PRIX_TRANSPORT	NUMERIC(6;2)	NOT NULL,
	CONSTRAINT PK_VILLAGE
					PRIMARY KEY(NOM_VILLAGE),
	CONSTRAINT FK1_CATEGORIE_VILLAGE
					FOREIGN KEY (NO_CATEGORIE)
					REFERENCES CATEGORIE_VILLAGE (NO_CATEGORIE)
);

/***********************************************************
	Table "LOGEMENT"
***********************************************************/
CREATE TABLE LOGEMENT
(
	NO_LOGEMENT			SMALLINT		NOT NULL,
	NOM_VILLAGE			VARCHAR2(15)	NOT NULL,
	CODE_TYPE_LOGEMENT	VARCHAR2(2)		NOT NULL,
	COMMENTAIRE			VARCHAR2(75)	NULL,
	CONSTRAINT PK_LOGEMENT
					PRIMARY KEY (NO_LOGEMENT, NOM_VILLAGE),
	CONSTRAINT FK1_TYPE_LOGEMENT
					FOREIGN KEY (CODE_TYPE_LOGEMENT)
					REFERENCES TYPE_LOGEMENT (CODE_TYPE_LOGEMENT)
	CONSTRAINT FK3_VILLAGE
					FOREIGN KEY (NOM_VILLAGE)
					REFERENCES VILLAGE (NOM_VILLAGE)
);
